### ISSUE TITLE
Did you pre-train SinMDM on the dataset, similar to MDM on HumanML3D

### ISSUE THREAD

**Issue by daidaiershidi** [SinMDM/SinMDM#10]
Did you pre-train SinMDM on the dataset, similar to MDM on HumanML3D.  Because it seems that SinMDM cannot use text as prompt now. I am curious if pre-training will allow the model to bring better generalization when generating actions.

**Comment by sigal-raab** [comment]
@daidaiershidi, thank you for your inquiry.  The key idea in SinMDM is that it is trained on a single motion sequence, allowing the learning of motions even when data is scarce. Therefore, we do not pre-train SinMDM on any dataset, hence it cannot use text as a control.
Supporting text prompts when training on a single motion is a good research direction for the future :)
