### ISSUE TITLE
train

### ISSUE THREAD

**Issue by Miao-WangHao** [SinMDM/SinMDM#12]
python -m train.train_sinmdm --arch unet --dataset mixamo --save_dir <'path_to_save_models'> --sin_path <'path to .bvh file for mixamo/bvh_general dataset or .npy file for humanml dataset'> --lr_method ExponentialLR --lr_gamma 0.99998 --use_scale_shift_norm --use_checkpoint

可以解释一下这个  --sin_path <'path to .bvh file for mixamo/bvh_general dataset or .npy file for humanml dataset'> 吗？有点迷糊，不知道是什么路径。

**Comment by SinMDM** [comment]
`--sin_path` is the path of the motion file you want to train on. This can either be a **bvh** file for mixamo or bvh_general datasets, or a **npy** file for humanml dataset. We provide motion files you can download by following [these instructions](https://github.com/SinMDM/SinMDM#get-data), or you can use a bvh file of your choice.

**Comment by Miao-WangHao** [comment]
我下载了完整的humanml3d数据集，然后是这样的：
~/work-miao/motion-diffusion-model/dataset/HumanML3D$ ls 
all.txt     joints    new_joints      Std.npy   texts.zip  train_val.txt
animations  Mean.npy  new_joint_vecs  test.txt  train.txt  val.txt

joints    new_joints  new_joint_vecs  这三个文件内是大量的.npy文件，但是我该如何选择呢？

**Comment by SinMDM** [comment]
Choose a file from new_joint_vecs folder. You can find the text description of each motion in the `text` folder.
For example:
`--sin_path dataset/HumanML3D/new_joint_vecs/000006.npy`

**Comment by Miao-WangHao** [comment]
很强阿，大佬。跑起来了，你很牛阿。棒棒的

**Comment by ZyzJinQu** [comment]
How should my own bvh file be structured in a uniform way with Mixamo's bvh file?

**Comment by SinMDM** [comment]
Your own file can be any valid bvh file. While training with a non-mixamo bvh, use the argument `--dataset bvh_general`.

**Comment by ZyzJinQu** [comment]
But does the different bvh bone structure inside affect training？Thank you for your reply!

**Comment by SinMDM** [comment]
SinMDM can be trained on any bone structure. The training is done on a single motion file, so there is no need to maintain coherence with any other bone structure.

**Comment by ZyzJinQu** [comment]
I'll give it a try, thank you very much for your reply!

**Comment by SinMDM** [comment]
Let me know if all worked as expected 🤩

**Comment by ZyzJinQu** [comment]
Hahahahahahahahaha, will definitely keep you posted. Super thanks!

**Comment by ZyzJinQu** [comment]
Thank you very much, it's working fine at the moment.
