### ISSUE TITLE
reproduce motion harmonization

### ISSUE THREAD

**Issue by Ozawakun97** [SinMDM/SinMDM#15]
I am Interested in the style transfer function of your work, and want to reproduce from motion "walk" to motion "walk happily" could you please tell me which motion and which pretrained model you used to achieve this? since it is not shown in the readme.md

**Comment by SinMDM** [comment]
Hello, 
Thank you for your interest, here are the relevant files to reproduce the "Happy walk" style transfer example:
- Happy walk motion used to pretrain the model- [Happy Walk.bvh](https://drive.google.com/file/d/1ksf1EIjm9oyGuDGvBqWeHNRhgopcOTyT/view?usp=drive_link). Place the bvh file under `dataset` folder.   
- [Pretrained model ](https://drive.google.com/file/d/1_Wt_YcrhOOYIgBcG0tAqrpH4VX0-GAwV/view?usp=sharing) and [args.json](https://drive.google.com/file/d/15_3dXiZACUzEsku1Y200w4bm_4p0-JiW/view?usp=sharing) file
- The walk motion the style was applied to: [Female_Tough_walk_long.bvh](https://drive.google.com/file/d/1UsoBY-P-aSkfu4qxclDCO6KgqboOXdy_/view?usp=drive_link)
