### ISSUE TITLE
Applications

### ISSUE THREAD

**Issue by ZyzJinQu** [SinMDM/SinMDM#16]
I tested In-betweening inside Applications, but no bvh file is generated inside, why is that? Is it possible that the individual features in Applications are only shown in video?

**Comment by SinMDM** [comment]
Dear @ZyzJinQu, 
Thank you for your interest.
Currently, the results of the applications are saved into mp4 files only.
However, there is an easy way for saving bvh files.

If you are using a mixamo or a bvh_general file, then do the following:
In file SinMDM/sample/edit.py, line 340, add the following:
   `BVH.save(<your choice of output path>, anim)`

if you are using a Humanml3D file, then follow [issue #32](https://github.com/GuyTevet/motion-diffusion-model/issues/32) at the [MDM repository](https://github.com/GuyTevet/motion-diffusion-model).

Hope this is helpful, let us know if you have further questions.

**Comment by ZyzJinQu** [comment]
Thank you very much for your reply!
Here is my code for testing In-betweening:python -m sample.edit --model_path . /save/test_in_betweening/betweening/model000059999.pt --edit_mode in_betweening --prefix_end 0.25 --suffix_start 0.25 --num_samples 1
Two questions for you.
1. I use the original motion to operate, prefix and suffix each 25%, but the generated bvh file is exactly the same as the original bvh motion trajectory, as if there is no in_betweening, why is this?
2. I changed the value of num_samples to 2, but it still generates only 1 bvh file, why is that?
Looking forward to your reply, thanks again for your work!

**Comment by SinMDM** [comment]
Dear @ZyzJinQu,
1. Please use `--suffix_start 0.75` (or any other number that is notably greater than 0.25).
2. Are you saving the bvh according to my instructions above? if yes, then please save with a different name in each iteration. If you are using a mixamo file (that is, if you used `--dataset mixamo` while training), then a bvh file is already saved in the output folder, with the name `sample0i.bvh` where `i` is the index of the sample.

**Comment by ZyzJinQu** [comment]
Thank you very much for your reply! If --suffix_start 0.75, --prefix_end 0.25 is unchanged, then the prefix and suffix are full, and the sum is 1. Wouldn't that have introduced all the original motion? (I used --bvh_general)

**Comment by ZyzJinQu** [comment]
For the second question, here's my test code: bvh.save(". /save/test_in_betweening/betweening/betweening.bvh", anim)
I'm wondering if I should use a variable to change the name of the bvh for each iteration?

**Comment by SinMDM** [comment]
The in_betweening framework takes frames [zero to prefix_end*length] and [suffix_start*length to length] from the input motion, and generates frames [prefix_end*length to suffix_start*length].
For example, say you have 80 frames.
Then for `--prefix_end 0.25 --suffix_start 0.75` You would get the following division:
frames 0-19:    fixed prefix based on the input motion.
frames 20-59: synthesized motion.
frames 60-79: fixed suffix based on the input motion.

Please let me know if this is more clear now.

**Comment by SinMDM** [comment]
> For the second question, here's my test code: bvh.save(". /save/test_in_betweening/betweening/betweening.bvh", anim) I'm wondering if I should use a variable to change the name of the bvh for each iteration?

Yes, please change the name for each iteration.

**Comment by ZyzJinQu** [comment]
I understand what you are saying! My understanding was a little off before. Thank you very much for your detailed, patient, and timely response! And thank you very much for the work you do! Once again, my respects to you! I will make a new attempt immediately! Thank you!

**Comment by ZyzJinQu** [comment]
I tested it the way you said, still using the same motion from the original training, here's the test code: python -m sample.edit --model_path . /save/test_in_betweening/betweening/model000059999.pt --prefix_end 0.25 --suffix_start 0.75 --edit_mode in_betweening --num_samples 1
Unfortunately, it still generates the exact same motion as the original.
This is where I added the code, I tried different indent positions and it still doesn't work. I hope you can reply! Thanks!
![QQ图片20230919165324](https://github.com/SinMDM/SinMDM/assets/49515254/2dc4b629-6d1b-4fa5-a201-99201a29d6e1)

**Comment by SinMDM** [comment]
My bad, the BVH saving command that I gave you saves the original motion.
Anyway, the output mp4 file should show the generated in_betweening result. 
**Does it show the expected result?**

To save the output bvh, you should do the following:
1. Clone [https://github.com/sigal-raab/Motion](https://github.com/sigal-raab/Motion).
2. Run the in_betweening code. (`python -m sample.edit <args>`)
3. Run the following function. Don't forget to put your own paths inside input_bvh and motion_path.
```
def mdm2bvh():
    from Motion.InverseKinematics import animation_from_positions
    from Motion import BVH
    input_bvh = <the bvh on which your network has been trained>
    input_anim, names, _ = BVH.load(input_bvh)
    motion_path = '<the in_betweening output path>/results.npy'
    pos = np.load(motion_path, allow_pickle=True)
    pos = pos.item()['motion']
    pos = pos.transpose(0, 3, 1, 2) # samples x joints x coord x frames ==> samples x frames x joints x coord
    parents = input_anim.parents  
    bvh_path = motion_path[:-4] + '_anim_{}.bvh'
        for i, p in enumerate(pos):
        print(f'starting anim no. {i}')
        anim, sorted_order, _ = animation_from_positions(p, parents)
        BVH.save(bvh_path.format(i), anim, names=names)
```

**Comment by ZyzJinQu** [comment]
Thank you very much for your reply! I did further testing and adjusted the indentation of the for a bit, as well as other requirements, and so far everything is working fine and the generated content meets the requirements. Thanks again for your reply and for all the work you do!
