### ISSUE TITLE
Hello! Can you please tell me how to create this display image.

### ISSUE THREAD

**Issue by ZyzJinQu** [SinMDM/SinMDM#18]
Hello! Can you please tell me how to create this display image. Looking forward to your reply!
![image](https://github.com/SinMDM/SinMDM/assets/49515254/5953edf2-1a9e-4a8d-9700-433b6f2e5617)

**Comment by ZyzJinQu** [comment]
May I ask how you made it? Thanks!

**Comment by SinMDM** [comment]
Hi @ZyzJinQu and thank you for your interest.
Please take a look at [issue #2](https://github.com/SinMDM/SinMDM/issues/2).
That issue provides instructions for displaying a skinned motion. 
If you have further questions, do let us know.

**Comment by ZyzJinQu** [comment]
Thank you very much for your reply! I want to ask you how to make the effect of the screenshot, such as the floor, the background and so on? Did you use Blender? Rather than redirecting questions about it. Thank you very much!

**Comment by SinMDM** [comment]
Yes, we used Blender. The floor, shadows, and so on, are all Blender effects.

**Comment by ZyzJinQu** [comment]
Thank you very much for your reply!
