### ISSUE TITLE
Couldn't connect bvh file in Blender with Mixamo fbx texture

### ISSUE THREAD

**Issue by huma0605** [SinMDM/SinMDM#19]
I am trying to follow https://github.com/SinMDM/SinMDM/issues/2 to visualize the generated bvh file in Blender.

Since the [mixamo_ref.fbx](https://drive.google.com/file/d/1s-cppg2pd3tVKWIxozP6jtxk05LFEhTI/view?usp=share_link) link is not available anymore, I am downloading Michelle character fbx directly from Mixamo.

My Blender version is 3.6.5. When I deleted the skeleton as instructed, the mesh will be in a T-pose, but became super large. And the bvh skeleton was very small compared to this big T-pose.

And when I selected the modifier and assign the generated bvh to it, it would not do anything. When playing the animation, only the generated bvh skeleton was moving.

Several random guess:
(1) Is it possible that it is due to the Blender version difference? Could you share what is your Blender version?
(2) With the downloaded Michelle character fbx from Mixamo, I noticed that the bone names are with prefix "mixamorig". For example, "mixamorig:Hips". But in the generated bvh file, the bone names are without the prefix, like "Hips".
(3) With the downloaded Michelle character, I noticed that it set the armature object with transform Rotation x 90, Scale X = 0.01, Scale y = 0.01, Scale z = 0.01. I think this is the reason why after removing the skeleton, the mesh became so big. I tried to transform the bvh generated skeleton by doing rotation x -90, scale x = y = z = 100. Now the orientation and the scale matches, but the modifier still do nothing.

Would appreciate for any guidance and suggestion.

**Comment by SinMDM** [comment]
Hi there, Please try this link to the [mixamo_ref.fbx](https://drive.google.com/file/d/1t_jWPtPlLgP_2Vqp8NqvTeTeW9mQgNbY/view?usp=sharing) and let me know if it works now.
