### ISSUE TITLE
can u tell me how to use the texture with your demo？

### ISSUE THREAD

**Issue by ywdong** [SinMDM/SinMDM#2]
great job！ I have run the script of sample.generate and generate some bvh file. I use the blender load the file，the motion is great， but not get the texture. How can i get the texture like your demo?
![image](https://user-images.githubusercontent.com/1457889/231173381-f6b0cbb1-1c06-4532-9df4-e23a7c1bc25d.png)

**Comment by wassryan** [comment]
+1

**Comment by SinMDM** [comment]
Hello,
Thank you for using our model, we're glad to hear that the motion is great!
To get the texture in Blender, you can follow these steps:

1. Import an FBX file that contains the mesh and texture to blender. For Mixamo motions, you can use this file: [mixamo_ref.fbx](https://drive.google.com/file/d/1s-cppg2pd3tVKWIxozP6jtxk05LFEhTI/view?usp=share_link)
2. Select only the skeleton of the imported FBX and delete it. The mesh will then appear in T-pose.
![image](https://user-images.githubusercontent.com/124880872/232765865-813c0468-db82-4d75-8992-c861aebe9501.png)
3. Import the BVH file that was generated by the model
4. Select the mesh, go to modifier properties, and press the tooltip icon. Then, select the generated BVH.
![image](https://user-images.githubusercontent.com/124880872/232766172-cde3673e-5a92-4285-9e8a-75ca395c5022.png)

That's it! 

We hope this helps, let us know if you have any further questions.

**Comment by ywdong** [comment]
> Hello, Thank you for using our model, we're glad to hear that the motion is great! To get the texture in Blender, you can follow these steps:
> 
> 1. Import an FBX file that contains the mesh and texture to blender. For Mixamo motions, you can use this file: [mixamo_ref.fbx](https://drive.google.com/file/d/1s-cppg2pd3tVKWIxozP6jtxk05LFEhTI/view?usp=share_link)
> 2. Select only the skeleton of the imported FBX and delete it. The mesh will then appear in T-pose.
>    ![image](https://user-images.githubusercontent.com/124880872/232765865-813c0468-db82-4d75-8992-c861aebe9501.png)
> 3. Import the BVH file that was generated by the model
> 4. Select the mesh, go to modifier properties, and press the tooltip icon. Then, select the generated BVH.
>    ![image](https://user-images.githubusercontent.com/124880872/232766172-cde3673e-5a92-4285-9e8a-75ca395c5022.png)
> 
> That's it!
> 
> We hope this helps, let us know if you have any further questions.

It's great. But if I use HumanML3D Dataset, it not fit  mixamo_ref.fbx. Any ideas?

**Comment by SinMDM** [comment]
Skinning for HumanML3D requires SMPL, which is currently not a dependency in our project. However, you can use the script provided by [MDM](https://github.com/GuyTevet/motion-diffusion-model#getting-started)- clone the repo and install the conda environment, then follow the instructions on how to [render the SMPL mesh](https://github.com/GuyTevet/motion-diffusion-model#render-smpl-mesh). The script requires the .mp4 file that was generated by the model.
