### ISSUE TITLE
arch

### ISSUE THREAD

**Issue by DisgustedALL** [SinMDM/SinMDM#24]
Thank you very much for the work you do. I would like to ask why 'Unet' and 'qna' are alone in the architecture parameter (--arch), while in the article it is a combination of the two to achieve the effect in the description. If I want to combine the two, as in the article, how should I choose the values of the parameters?Looking forward to your reply.

**Comment by sigal-raab** [comment]
Hi @ZyzJinQu and thank you for your interest.
To use the UNet architecture with qna blocks, one should specify the following arguments in the command-line:
--arch_unet --use_attention --use_qna.
I will change the documentation to explain this better.
Please let me know if this worked for you.
Best, 
Sigal

**Comment by ZyzJinQu** [comment]
Thank you very much for your reply, but I am getting the following error in my attempts, looking forward to your reply, thank you very much!
![image](https://github.com/SinMDM/SinMDM/assets/49515254/cb4e8148-789b-4125-87c5-7b2937727c64)
![image](https://github.com/SinMDM/SinMDM/assets/49515254/2b98bb0e-4516-4807-9b5e-f258f33621f8)

**Comment by sigal-raab** [comment]
Correction: `use_attention` and `use_qna` are already True by default, so you don't need to specify them. 
The reason for the error you have seen is that these two arguments expect an argument, such as False or True.
But anyhow, you don't need to specify them.

**Comment by ZyzJinQu** [comment]
Does this mean that (--arch unet) already combines unet with qna? without needing to specify otherwise.
![image](https://github.com/SinMDM/SinMDM/assets/49515254/6ae9d819-c2b1-4932-ab96-4cd16fb8beaf)

**Comment by ZyzJinQu** [comment]
Thank you very much for your reply! But my attempts in practice always produce a sudden turn at some point, and the overall effect doesn't live up to the natural presentation shown in your document. Hahahahahaha!

**Comment by sigal-raab** [comment]
I am sorry to hear that. This happens in rare cases. On some motion sequences, alternate architectures work better. I suggest you try `--arch qna` OR `--arch unet --channel_mult 1,2` OR `--arch unet --num_res_blocks 2`.
Please let me know if any of these alternatives produced better results.

**Comment by ZyzJinQu** [comment]
I will try that, thank you very much for your reply!

**Comment by ZyzJinQu** [comment]
Hello author, thank you for your outstanding work! I would like to see the log message (log.txt progress.csv), but for some reason it is always empty.

**Comment by Inbal-leibovitch** [comment]
Hello, 
The messages are printed out to the console, you can save the stdout to a file if you would like.
Could you please point us to where you see the files log.txt and progress.csv?

**Comment by ZyzJinQu** [comment]
Thank you very much for your outstanding work! I found the file in the following directory. logging to /tmp/openai-2024-03-09-16-14-08-187133
![image](https://github.com/SinMDM/SinMDM/assets/49515254/c9fb7c86-5e74-415a-a7a4-02b0b8e686ea)

**Comment by ZyzJinQu** [comment]
> I am sorry to hear that. This happens in rare cases. On some motion sequences, alternate architectures work better. I suggest you try `--arch qna` OR `--arch unet --channel_mult 1,2` OR `--arch unet --num_res_blocks 2`. Please let me know if any of these alternatives produced better results.

--arch unet --channel_mult 1,2   It feels like it produces better results.

**Comment by sigal-raab** [comment]
> --arch unet --channel_mult 1,2 It feels like it produces better results.

According to these results, a slightly wider receptive field (obtained with a deeper network) works better for your skeleton. I guess you either have a skeleton with many joints (say, more than 100) and/or a motion with abrupt changes. But it is hard to tell without seeing the input motion.

**Comment by ZyzJinQu** [comment]
Thank you very much for your outstanding work and also for your detailed answers.

**Comment by GuangtaoLyu** [comment]
> I am sorry to hear that. This happens in rare cases. On some motion sequences, alternate architectures work better. I suggest you try `--arch qna` OR `--arch unet --channel_mult 1,2` OR `--arch unet --num_res_blocks 2`. Please let me know if any of these alternatives produced better results.

i saw the qna in your train_eval_humanml_benchmark.sh. but the arch in the pretrained models is unet?
 
what is the final hyperparameter in your paper? 


![image](https://github.com/SinMDM/SinMDM/assets/57834464/f6847135-7cdd-45db-95b4-0c24eb0f255e)

**Comment by Inbal-leibovitch** [comment]
Hello,
The provided script is an example, you can change the parameters to train different versions of the model. 
The uploaded pretrained models use the unet architecture, which is also the architecture we describe in the paper. Please see the paper appendix for details of other hyperparameters used.
