### ISSUE TITLE
how to cal the Harmonic Mean?

### ISSUE THREAD

**Issue by GuangtaoLyu** [SinMDM/SinMDM#26]
I run train_eval_humanml_benchmark.sh. The results include intra_diversity, gt_intra_diversity, intra_diversity_gt_diff, inter_diversity and sifid. Lack of the Harmonic Mean. how to cal the Harmonic Mean?

**Comment by sigal-raab** [comment]
Dear @GuangtaoLyu,
Thank you for your interest.
You first need to normalize the scores you have computed. 
Normalization values were determined to be the 90% percentile of scores using various architectures.
Here they are: 
sifid_norm_val = 11.889, inter_div_norm_val =  1.67, intra_div_diff_norm_val =  1.151

Say your scores are sifid_score, inter_div_score, intra_div_div_score.
For Inter Div., higher is better, so it's a simple normalization: inter_div_normed = inter_div_score/inter_div_norm_val.
For the other two, lower is better, so we need to convert them before normalizing: x_normed =  (x_norm_val- x_score) / x_norm_val, where x is either sifid or intra_div_diff.

Finally, you compute the harmonic mean:
HM = 3 / (1/sifid_normed + 1/inter_div_normed + 1/intra_div_diff_normed.

**Comment by GuangtaoLyu** [comment]
> Normalization values were determined to be the 90% percentile of scores using various architectures.

"Normalization values were determined to be the 90% percentile of scores using various architectures."  
what are the scores using various architectures? 
can you share a script?

i run the train_eval_humanml_benchmark.sh. and then what should i do for computing the harmonic mean?

**Comment by sigal-raab** [comment]
We computed the harmonic mean in an Excel sheet. You are welcome to do the same, using the formulas in my previous answer.

**Comment by GuangtaoLyu** [comment]
![image](https://github.com/SinMDM/SinMDM/assets/57834464/1b7840e7-60f5-4f95-9d54-5e2bc55a71e5)

can you tell me how to compute the harmonic mean like the table 2 or table 1?

1. Normalization values were determined to be the 90% percentile of scores using various architectures.
Does this mean the 90% percentage of the results of the different compared methods in the table 2？
what are the 90% percentile of scores in the table 2?

**Comment by Inbal-leibovitch** [comment]
The 90% percentile was computed using the results of various architectures, including the ones shown in the table. 
The values for the table you attached, as mentioned in a previous comment, are: 

> sifid_norm_val = 11.889, inter_div_norm_val = 1.67, intra_div_diff_norm_val = 1.151

So to calculate the harmonic mean you can use these values to normalize the metrics and then follow the formula as described here:
> Say your scores are sifid_score, inter_div_score, intra_div_div_score. For Inter Div., higher is better, so it's a simple normalization: inter_div_normed = inter_div_score/inter_div_norm_val. For the other two, lower is better, so we need to convert them before normalizing: x_normed = (x_norm_val- x_score) / x_norm_val, where x is either sifid or intra_div_diff.
> 
> Finally, you compute the harmonic mean: HM = 3 / (1/sifid_normed + 1/inter_div_normed + 1/intra_div_diff_normed.
