### ISSUE TITLE
Diffusion model architecture

### ISSUE THREAD

**Issue by y0ngw00** [SinMDM/SinMDM#27]
Hi, I read your paper and got a good insight from your work. Thank you for sharing your work and code.

I have a question about the model architecture including so many layers of ResBlock(Sorry about this topic. It would be out of your main contribution.)
I'm not familiar with diffusion models, and I'd like to know the needs of deep layers and ResBlocks.
In the one of [previous motion diffusion models](https://github.com/GuyTevet/motion-diffusion-model), they used 4-8 layers with Transformers. 
However, recent papers like yours include 10-20 layers of ResBlocks. 
I have no idea of any reasoning about these changes of model architectures. It seems to be heavy, and I'd like to know the recent flows in this domain.
Is it not enough to use just a few layers of transformers for synthesizing motions?
Since I don't have any insights in this domain, I'm sorry in advance if it is too stupid question. :)

**Comment by Inbal-leibovitch** [comment]
Hello,
Thank you for your interest in our paper. 
Regarding your question about ResBlocks, note that in our architecture the number of resBlocks is set by `num_res_blocks` which we set to 1. You can see the other hyperparameters values in the paper appendix or by looking at the default values in `utils/parser_util.py`

**Comment by y0ngw00** [comment]
Thank you.
