### ISSUE TITLE
About --dataset mixamo

### ISSUE THREAD

**Issue by PeterWangyi** [SinMDM/SinMDM#28]
Hello and thank you for your great work!

I want to ask a question about data:
I have observed that if I use the same bvh data of mixamo, if I specify --dataset mixamo during command line training, the effect will be better and the convergence speed will be faster than when --dataset bvh_general. Even if it's the same bvh data.

Maybe you know what could be the reason?

**Comment by PeterWangyi** [comment]
thank you for your reply!

During training, when a mixamo bvh file is trained using --arch unet --dataset mixamo, the initial step[0]:loss[0.28], and the loss will converge to a very small value after 120_000 steps. .
The initial stage of training is as follows:
![企业微信截图_17158282671508](https://github.com/SinMDM/SinMDM/assets/90747373/2c2b13d1-cbd4-4f4a-b822-dc9368fa411f)

According to your tips, I tried to define the corresponding variables in skeleton_database.py based on my own bvh file. But when I use --arch unet --dataset mixamo to train on my bvh file, step[0]:loss[70], the loss will only converge to 0.28 after 120_000. This is bad, I only have 22 bones and the motion shape is (150, 300). I don't think this is a problem caused by the number of bones.
The initial stage of training is as follows:
![企业微信截图_17158285042103](https://github.com/SinMDM/SinMDM/assets/90747373/6c2efa2b-6d5e-467a-9911-47ff600f0e19)




After noticing this, I retaregt my bvh file onto the Mixamo bones again, and this time it worked great. . .step[0]:loss[0.3] So this should prove that it is not a problem of action distribution.

Maybe you have any suggestions?

**Comment by Inbal-leibovitch** [comment]
It is hard to tell without seeing your bvh file and what variables you defined in `skeleton_database.py`. If the bvh file you want is not from Mixamo I would suggest to use the `--dataset bvh_general` option.

**Comment by PeterWangyi** [comment]
Thank you for your reply!

Here is my bvh file(can't up load .bvh here)[Basic_Dai_dance.txt.txt](https://github.com/SinMDM/SinMDM/files/15332439/Basic_Dai_dance.txt.txt)

And my skeleton_database.py 
[skeleton_database.txt](https://github.com/SinMDM/SinMDM/files/15332596/skeleton_database.txt)

I found in the experiment just now that in my current bvh and skeleton_database definition mode, there is not much difference in the performance of my bvh using --dataset mixamo and --dataset bvh_general.

I read through the code for processing the data part, and I want to know, when using --dataset mixamo, in addition to the joint_reduction and feature (to_tensor) parts, is there any special processing for mixamo bvh?

Looking forward to your reply!

**Comment by Inbal-leibovitch** [comment]
You can see the additional processing done for mixamo dataset in the MotionData class.
I cannot tell from your files why you would have a problem. Did you look at the quality of the generated motions?
