### ISSUE TITLE
Data discrepancy using download_humanml3d_dataset.sh vs HumanML3D 

### ISSUE THREAD

**Issue by huma0605** [SinMDM/SinMDM#29]
For `dataset/humanml3d_single/npy/0000_a_person_picks_something_up_with_their_right_hand,_and_wipes_down_the_item_with_their_left.npy`, we can find its original HumanML3D entry `001803.npy`.

But when trying with `001803.npy`, the result would be totally meaningless (the skeleton would be floating forward).

When digging into these 2 .npy files, we found that `0000_a_person_picks_something_up_with_their_right_hand,_and_wipes_down_the_item_with_their_left.npy` contains more fields like "motion_raw" and "motion_xyz".

In `data_utils/data_util.py`, we can find that it is using "motion_raw".  But even if we transpose the data in `001803.npy`, it still not matches "motion_raw".

May we ask how did you derive this "motion_raw" data?

**Comment by Inbal-leibovitch** [comment]
Hello,
Under HumanML3D you should have two folders that include `.npy` files - `new_joint_vecs` and `new_joints`. You need to use the .npy file under **`new_joint_vecs`** folder. The following processing will be done:

https://github.com/SinMDM/SinMDM/blob/75abd8daddf8d2479c31450a8193076ccf3ac737/data_utils/data_util.py#L14-L17

The resulting values should be the same as "motion_raw" in the benchmark file.

**Comment by huma0605** [comment]
@Inbal-leibovitch  Thanks for the quick response! I did follow the mentioned processing with using the .npy file under `new_joint_vecs`, with the following simple script. I have attached those 2 .npy files here with the 001803's text description "a person picks something up with their left hand, and wipes down the item with their right." See `sinmdm_data_consistency.zip`.

```python
import numpy as np

original_data_file = "dataset/humanml3d_single/npy/001803.npy"
example_data_file = "dataset/humanml3d_single/npy/0000_a_person_picks_something_up_with_their_right_hand,_and_wipes_down_the_item_with_their_left.npy"

original_motion = np.load(original_data_file)  # only motion npy
if len(original_motion.shape) == 2:
    original_motion = np.transpose(original_motion)
    original_motion = np.expand_dims(original_motion, axis=1)

example_motion = np.array(np.load(example_data_file, allow_pickle=True)[None][0]['motion_raw'][0])  # benchmark npy

print(original_motion.shape, example_motion.shape)
```
The output shapes are `(263, 1, 199) (263, 1, 192)`.

If we try to print the first frame data, we can also clearly see the numerical differences. See `original_vs_example.txt`.
`original_motion[:, :, 0]` and `example_motion[:, :, 0]`.

Could you help double check if there is any additional processing on top of `001803.npy` from the `new_joint_vecs`?

A side note, we did use these humanml data to try MDM, and it was working fine. And the visualization by using `recover_from_ric` was also looking fine. That is the reason why we were wondering if there are some additional processing for SinMDM?

Appreciate for any guidance!

[sinmdm_data_consistency.zip](https://github.com/SinMDM/SinMDM/files/15368787/sinmdm_data_consistency.zip)
[original_vs_example.txt](https://github.com/SinMDM/SinMDM/files/15368801/original_vs_example.txt)

**Comment by yaohunghuberttsai** [comment]
Yeah, having the same problem here. It seems the `.npy` file under `new_joint_vecs ` is different from the given example `.npy`. What has been done to obtain `motion_raw`? 

And directly train SinMDM on the `.npy` file under `new_joint_vecs ` does not work (the generated motion looks weird and drifts a lot). While training SinMDM for the given example `.npy` does work.

**Comment by yaohunghuberttsai** [comment]
@Inbal-leibovitch , ping you here since the question is marked as complete. But I do want to get the answers from my questions. Thanks!
