### ISSUE TITLE
Postprocessing issue: retargeting the truebone zoo data samples

### ISSUE THREAD

**Issue by YiLin32Wang** [SinMDM/SinMDM#31]
Hi there,

Thanks for your nice work!

I'm currently trying to produce some visualization demos on the Truebone zoo data samples, but have some problems with retargeting the generated bvh source to the fbx file provided in Truebone zoo. 

As shown in the figure below, I'm testing the retargeting (with Rokoko) using exactly the same motion as the fbx(provided as bvh in the dataset). The first row is the original skeleton and skin mesh in fbx file; second row is after correcting the bone orientation when loading fbx; third row is the bvh source they provide in their dataset. 

The retargeting results using Rokoko are as the two columns in the last row. The retargeted armature is not correct. 
I've also tried to transfer the fbx with orientation corrected skeleton to bvh file, resulting in exactly the same skeleton structure. And then retarget this bvh to the fbx armature. But the retargeting with Rokoko still fails. 

I'm wondering if you have come across this problem before, and if you have any idea of the solutions?
<img width="786" alt="image" src="https://github.com/SinMDM/SinMDM/assets/91527702/4485db40-639b-40a8-90c2-f4fee7662a95">

**Comment by sigal-raab** [comment]
Hi @YiLin32Wang,
Apologies for the late reply.
Have you tried our utils/fbx2bvh.py conversion?
We are unfamiliar with Rokoko, so sadly, I don't think we can help here.
Regards,
Sigal
