### ISSUE TITLE
bpy <> python3.8 compatibility

### ISSUE THREAD

**Issue by rshen36** [SinMDM/SinMDM#32]
There are [no compatible releases](https://pypi.org/project/bpy/#history) of bpy with python3.8. If I wanted to use the `utils.fbx2bvh.py` script or programmatically perform the [.bvh binding to a reference .fbx file](https://github.com/SinMDM/SinMDM?tab=readme-ov-file#adding-texture-in-blender), what would be the recommended way of doing so? How important are the exact dependency versions specified in the `environment.yml` file?

**Comment by sigal-raab** [comment]
Hi @rshen36,

The file environment.yml file lists versions on which we successfully ran SinMDM. However, It is not important to use those exact versions. Whatever works for you is ok.

Unfortunately running scripts that use bpy is tricky and often fails in environments not within Blender. An easy workaround is to run them from Blender itself, either 
- from Blender's internal console, or 
- from command line: `<path to Blender> -b -P <your python script>`

Best,
Sigal
