### ISSUE TITLE
how to train a flying, dancing dragon model

### ISSUE THREAD

**Issue by wassryan** [SinMDM/SinMDM#4]
great job! Can you tell me how to train a flying or dancing dragon model.

**Comment by SinMDM** [comment]
To train a flying dragon you can use this bvh file [Wyvern-Fly.bvh](https://drive.google.com/file/d/1shkd1Yiu-6D9z_SZbBLSHjowknK_vDjZ/view?usp=share_link).
You can also use the `utils/fbx2bvh.py` script to convert any fbx provided in the truebones dataset to bvh format. 
Then use the training command:
`
python -m train.train_sinmdm --arch qna --dataset bvh_general --save_dir <path_to_save_models>  --sin_path <path to .bvh file>
`
