### ISSUE TITLE
Style transfer

### ISSUE THREAD

**Issue by yimengliu0216** [SinMDM/SinMDM#6]
Thanks for the great work! 
How's the style transfer model trained? Do you plan to release the trained model?

**Comment by yimengliu0216** [comment]
Thanks very much for the explanations! Do you know where we can find motions that could be used as styles? 

Sorry about the confusion. I wanted to ask about the trained models for style transfer.

**Comment by SinMDM** [comment]
You can use any motion you like as a style. You can use the motions we provided under [Get Data](https://github.com/SinMDM/SinMDM#get-data) section, or download motions directly from [Mixamo](https://www.mixamo.com/#/) and use `utils/fbx2bvh.py` to convert fbx files to bvh files.

We also provide various [trained models](https://github.com/SinMDM/SinMDM#download-pretrained-models) which you can use for style transfer.

**Comment by yimengliu0216** [comment]
Thanks very much!
