### ISSUE TITLE
Pretrained weights 

### ISSUE THREAD

**Issue by abhigoku10** [SinMDM/SinMDM#7]
@SinMDM  thanks for sharing wonderful work is it possible to share the pretrained to test the model either thru google drive or onedrive 
THnsk in advance

**Comment by sigal-raab** [comment]
Dear @abhigoku10, 
Thank you for the warm words.
The pre-trained models are already shared in this repository, [here](https://github.com/SinMDM/SinMDM#download-pretrained-models).
Regards,
Sigal

**Comment by SinMDM** [comment]
Dear @abhigoku10,
Thank you for the warm words.
The pre-trained models are already shared in this repository, [here](https://github.com/SinMDM/SinMDM#download-pretrained-models).
Regards,
The SinMDM team
