### ISSUE TITLE
Why conv_1d is not working well?

### ISSUE THREAD

**Issue by hwangdonghyun** [SinMDM/SinMDM#8]
Before I ask the question, thank you for your great work.
When I read the code, I observed that the architecture is working with conv2D operations, unlike other motion works that use conv1d as the main operator.
Of course, I understand this because the QnA architecture is for the image task.
But even with the U-net architecture, it uses conv2d operators with the default settings.
I tried option conv_1d to train the u-net architecture, but the loss is higher than conv2d u-net.
I want to know the theoretical background that you make to use the conv2d in the motion domain.
Also, it's so thankful, if you provides ideas or related works that use conv2d in motion generation.

**Comment by SinMDM** [comment]
Thank you for your feedback. The default value of the conv_1d argument when using Unet is indeed false, and should be redesigned to have a default value of True.
In our Unet experiments, we found that using 1D convolutions yielded better results with significantly faster running time compared to using 2D convolutions.
However, 2D convolutions are particularly useful when the convolution is "Skeleton-Aware", where each joint is convolved with its neighboring joints in the skeleton. While not mandatory, using 2D convolutions in such cases provides a more intuitive approach. For instance, in [MoDi](https://github.com/sigal-raab/MoDi), a skeleton-aware motion synthesis network, 3D convolution operators are employed.

We hope this clarifies the matter.
SinMDM team

**Comment by hwangdonghyun** [comment]
Thanks for your kind answer :)
